name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run one line code
      run: echo azul Adel
    - name: Run two lines
      run: |
        echo a line 1
        echo test line 2